In [1]:
# This script processes potential duplicated stations using produced subset of distance matrix containing only stations which have at least one other station in range < threshold 
# distance (saved in output_data: duplicated_only_distmatrix_0.25km.pkl)

# 1. read in filtered merged water quality raw data and merged station data and calculate some stats to get an overview of available stations
# 2. read in by threshold subsetted distance matrix to filter potential_duplicated "station_pairs"
# 3. calculate a list of all potential duplicated stations (station pairs with distance < threshold) from subsetted distance matrix
# 4. filter this list and exclude pairs where stations are paired with themself e.g. GRQA Id_01 and GRQA Id_01 -->  have a distance of 0.0km 

# 5. read in again merged station data: but now assigned to stream_ids from HydroRiver shapefile (this file is produced  using notebook "p_06_assign_stations_to_HydroRivers.ipynb"
# and can be find in cnp-synthesis\output_data\assign_stations_HydroRivers\ArcPy_output
# 6. Merge pairs of potential duplicated stations and stations dataset containing infos about countries, dataset, assigned river_id
# 7. save list of all pot_duplicated_stations with all the added infos as csv and additionally a list of station pairs with different countries as well

In [2]:
# load required modules:

import pandas as pd
from glob import glob
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import Point
import warnings
from tqdm import trange
from time import time
import pickle
from scipy.spatial.distance import cdist
from scipy.spatial import distance_matrix
import pdb
from math import sin, cos, sqrt, atan2, radians
from scipy.spatial.distance import pdist, squareform
from sklearn.metrics.pairwise import pairwise_distances
import multiprocessing
from multiprocessing import Pool
n_cores = multiprocessing.cpu_count()
import os
from tqdm import tqdm
from time import time

In [14]:
# define the output folder path:

output_folder = '../../output_data/merge_0km_dist_stations'

# Check if the folder exists, if not, create it:
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

 ## 1. read in merged water quality raw data and merged station data and calculate some stats to get an overview of available stations

In [4]:
#--- Stations Data ---
tic = time()
stations = gpd.read_file('../../output_data/merged_datasets/stations.shp')
stations = stations.set_index(['dataset','site_id']).sort_index()
stations = stations.reset_index()
stations['site_id'] = stations['site_id'].astype(str)
stations = stations.set_index(['dataset','site_id'])
print('Block time [seg]: ',f'{time()-tic}')

Block time [seg]:  0.9361817836761475

In [5]:
#--------------- WATER QUALITY PROCESSING------------ ########################
# read in merged raw data:
tic = time()
raw_data = pd.read_csv('../../output_data/merged_datasets/filtered_merged_raw_data.csv')
raw_data = raw_data.set_index(['dataset', 'site_id']).replace(-9999,np.nan).sort_index()
raw_data['obs_date'] = pd.DatetimeIndex(raw_data['obs_date'].values)
print('Loaded raw data in [sec]: ', f'{time() -tic}')



# ----id's to string----

raw_data = raw_data.reset_index()
raw_data['site_id'] = raw_data['site_id'].astype(str)
raw_data = raw_data.set_index(['dataset', 'site_id'])


# ---change the Ob' of arcticdeltas data
raw_data = raw_data.reset_index()
raw_data['site_id'] = raw_data['site_id'].replace('Ob\'','Ob').values

# get sorted index
raw_data = raw_data.set_index(['dataset', 'site_id']).sort_index()
raw_data_index = raw_data.sort_index().index.unique()
print("Block time [sec]: ",f'{time()-tic}')

C:\Users\bartusch\AppData\Local\Temp\ipykernel_4612\3324177926.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('../../output_data/merged_datasets/filtered_merged_raw_data.csv')

Loaded raw data in [sec]:  9.244240999221802
Block time [sec]:  12.822776317596436

In [6]:
#--- Obtain stats of compounds we are interested per station ---
tic = time()
stations_index = stations.index
output = []
#compounds = raw_data.columns.to_list()[4:]
compounds = ['NH4N','NO3N','NO2N','TOC','DOC','TP','DIP', 'OPO4']
for comp in compounds:
    print(comp)
    raw_data[comp] = raw_data[comp].astype(float).values
    aux_data = raw_data[[comp,'obs_date']].copy().dropna()
    group = aux_data.groupby(level=[0,1])
    median = group.median()[[comp]].rename(columns={comp:f'{comp}_median'})
    q25 = group.quantile(0.25)[[comp]].rename(columns={comp:f'{comp}_25'})
    q75 = group.quantile(0.75)[[comp]].rename(columns={comp:f'{comp}_75'})
    n = group.count()[[comp]].rename(columns={comp:f'{comp}_n'})
    start = group.min()[['obs_date']].rename(columns={'obs_date':f'{comp}_start'})
    end = group.max()[['obs_date']].rename(columns={'obs_date':f'{comp}_end'})
    stats = pd.concat([median,q25,q75,n,start,end],axis=1)
    cols = stats.columns
    output.append(stats.copy())
stations_stats = pd.concat(output,axis=1)
print("Elapsed %.2f seconds" % ((time() - tic)))

NH4N
NO3N
NO2N
TOC
DOC
TP
DIP
OPO4
Elapsed 4.25 seconds

In [7]:
#print(stations_stats)

## Set threshold: distance pot duplicated

In [8]:
thrs = 0.25 # else 0.5

## 2. Read in subsetted distance matrix (adapt filename corresponding to threshold)

In [10]:
# subset of distance matrix:
# ---load distance matrix ----
tic = time()
stations_dup_km_2 = pickle.load(open(f'../../output_data/duplicated_only_distmatrix_{thrs}km.pkl', 'rb'))
print("Elapsed %.2f seconds" % ((time() - tic)))
#print(dist_matrix.shape,stations_stats.shape)

Elapsed 1.41 seconds

## 3. calculate a list of all potential duplicated stations (station pairs with distance < threshold) from subsetted distance matrix

In [11]:
# loop over all columns of subsetted distance matrix to get all duplicates:
cols = stations_dup_km_2.columns

all_A = []
all_B = []
all_distances = []
for i in cols:
    inds_thrs = stations_dup_km_2[stations_dup_km_2[i]<=thrs].index.to_list()
    # select rows of stations with distance smmaller threshold to station in column i
    rows_distance = stations_dup_km_2[(stations_dup_km_2[i] <= thrs)]
    # Extract the values from column 'i' from filtered rows containing distances<threshold
    distances = rows_distance[i]
    length = len(inds_thrs)
    station_A = [i] * length
    station_B = inds_thrs
    all_A.extend(station_A)
    all_B.extend(station_B)
    all_distances.extend(distances)
# organise in a dataframe
pot_duplicated_stations = pd.DataFrame({'station_id_a':all_A, 'station_id_duplic':all_B, 'distance_km':all_distances})
# define data types
pot_duplicated_stations['station_id_a'] = pot_duplicated_stations['station_id_a'].astype(str)
pot_duplicated_stations['station_id_duplic'] = pot_duplicated_stations['station_id_duplic'].astype(str)
pot_duplicated_stations['distance_km'] = pot_duplicated_stations['distance_km'].astype(str)

In [12]:
print(pot_duplicated_stations) 
# 69966 rows in pot_duplicated_stations (threshold 0.5km)--> but has to be filtered
# 45356 rows in pot_duplicated_stations (threshold 0.25km)--> but has to be filtered

             station_id_a          station_id_duplic distance_km
0      ('GRQA', '100002')         ('GRQA', '100002')         0.0
1      ('GRQA', '100002')  ('GRQA', 'USGS-01017100')       0.147
2      ('GRQA', '100003')         ('GRQA', '100003')         0.0
3      ('GRQA', '100003')  ('GRQA', 'USGS-01017500')       0.036
4      ('GRQA', '100004')         ('GRQA', '100004')         0.0
...                   ...                        ...         ...
45351    ('sweden', '66')           ('sweden', '60')      0.1613
45352    ('sweden', '66')           ('sweden', '66')         0.0
45353     ('sweden', '7')            ('sweden', '2')      0.0146
45354     ('sweden', '7')            ('sweden', '6')      0.2327
45355     ('sweden', '7')            ('sweden', '7')         0.0

[45356 rows x 3 columns]

## 4. Filter list of  "station pairs" --> stations that are potential duplicates

In [13]:
# -----create subset of all stations that are potential duplicates: ----- 

# this line excludes rows from dataframe if both are same station id's: e.g.: 'GRQA', '100586' and 'GRQA', '100586'
duplicated_stations_3 = pot_duplicated_stations.iloc[pot_duplicated_stations[pot_duplicated_stations['station_id_duplic']!=pot_duplicated_stations['station_id_a']].index,:]
print(duplicated_stations_3)
print(duplicated_stations_3.info())

# next step: each pair of potential duplicated stations_id with distance of 0km occurs two times in dataframe
# these duplicates must be removed:

# convert station id's to strings
combined_correct = duplicated_stations_3['station_id_a'].astype(str) + duplicated_stations_3['station_id_duplic'].to_list()
combined_inverted = duplicated_stations_3['station_id_duplic'].astype(str) + duplicated_stations_3['station_id_a'].to_list()

# filter only one version of all station combinations

duplicated_stations_4 = duplicated_stations_3.copy()
duplicated_stations_4.columns = ['x','y', 'distance_km']
print(duplicated_stations_4.columns)

duplicated_stations_4.loc[:,'filter'] = duplicated_stations_4.loc[:,['x','y']].apply(lambda row: '-'.join(sorted(row, key=lambda char: char)), axis=1)
 # save all pairs to                                                                     
pairs_pot_duplicated = duplicated_stations_4.drop_duplicates(subset=['filter']).reset_index()[['x','y','distance_km']]
# contains 48516 pot duplicated station pairs (threshold 0.5km)

             station_id_a          station_id_duplic distance_km
1      ('GRQA', '100002')  ('GRQA', 'USGS-01017100')       0.147
3      ('GRQA', '100003')  ('GRQA', 'USGS-01017500')       0.036
5      ('GRQA', '100004')         ('GRQA', '110876')      0.0124
6      ('GRQA', '100004')         ('GRQA', '110877')      0.0124
7      ('GRQA', '100004')       ('GRQA', 'CAN00052')      0.1286
...                   ...                        ...         ...
45348    ('sweden', '61')           ('sweden', '62')      0.1192
45349    ('sweden', '62')           ('sweden', '61')      0.1192
45351    ('sweden', '66')           ('sweden', '60')      0.1613
45353     ('sweden', '7')            ('sweden', '2')      0.0146
45354     ('sweden', '7')            ('sweden', '6')      0.2327

[30130 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 30130 entries, 1 to 45354
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   station_id_a       30130 non-null  object
 1   station_id_duplic  30130 non-null  object
 2   distance_km        30130 non-null  object
dtypes: object(3)
memory usage: 941.6+ KB
None
Index(['x', 'y', 'distance_km'], dtype='object')

#### Save data:

In [15]:

# print info of pot_duplicated stations: 
print(pairs_pot_duplicated.info())
print(pairs_pot_duplicated)
# save file to csv: 
pairs_pot_duplicated.to_csv(f'../../output_data/merge_0km_dist_stations/all_pairs_of_potential_dup_stations_{thrs}km.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15065 entries, 0 to 15064
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   x            15065 non-null  object
 1   y            15065 non-null  object
 2   distance_km  15065 non-null  object
dtypes: object(3)
memory usage: 353.2+ KB
None
                        x                          y distance_km
0      ('GRQA', '100002')  ('GRQA', 'USGS-01017100')       0.147
1      ('GRQA', '100003')  ('GRQA', 'USGS-01017500')       0.036
2      ('GRQA', '100004')         ('GRQA', '110876')      0.0124
3      ('GRQA', '100004')         ('GRQA', '110877')      0.0124
4      ('GRQA', '100004')       ('GRQA', 'CAN00052')      0.1286
...                   ...                        ...         ...
15060     ('sweden', '2')            ('sweden', '7')      0.0146
15061    ('sweden', '58')           ('sweden', '59')       0.227
15062     ('sweden', '6')            ('sweden', '7')      0.2327
15063    ('sweden', '60')           ('sweden', '66')      0.1613
15064    ('sweden', '61')           ('sweden', '62')      0.1192

[15065 rows x 3 columns]

In [16]:
# Get number of different Station_id's in x and y: 

unique_station_ids = pd.concat([pairs_pot_duplicated['x'], pairs_pot_duplicated['y']]).unique()
print(f'A number of, {len(unique_station_ids)} stations has duplicated stations in distance of {thrs} km')


# get number n of stations that are at same location : How many stations are at same location? für jede Station x wie oft kommt sie vor,
# also wie viele Stationen sind an der Position 
all_occurences = pd.concat([pairs_pot_duplicated['x'], pairs_pot_duplicated['y']])
#all_occurences.groupby('category')['value'].transform('sum')

all_o = pd.DataFrame({'ocurrences':all_occurences})
menge = all_o.groupby("ocurrences").size().reset_index(name="Anzahl")
print(menge)
# maximum 49 stations at same position GRQA NL05--> example, would be interesting to know what is different ?
menge[menge['Anzahl']==49]
#menge.groupby('Anzahl').count().sort('occurences')

# A number of, 21450 stations has duplicated stations in distance of 0.5km
# A number of, 15226 stations has duplicated stations in distance of 0.25 km

A number of, 15226 stations has duplicated stations in distance of 0.25 km
               ocurrences  Anzahl
0      ('GRQA', '100002')       1
1      ('GRQA', '100003')       1
2      ('GRQA', '100004')       6
3      ('GRQA', '100005')       1
4      ('GRQA', '100007')       1
...                   ...     ...
15221    ('sweden', '60')       1
15222    ('sweden', '61')       1
15223    ('sweden', '62')       1
15224    ('sweden', '66')       1
15225     ('sweden', '7')       2

[15226 rows x 2 columns]

                   ocurrences  Anzahl
3706  ('GRQA', 'NL05_01_009')      49
3707  ('GRQA', 'NL05_01_026')      49
3708  ('GRQA', 'NL05_01_037')      49
3711  ('GRQA', 'NL05_02_006')      49
3713  ('GRQA', 'NL05_02_037')      49
3714  ('GRQA', 'NL05_02_039')      49
3715  ('GRQA', 'NL05_02_046')      49
3716  ('GRQA', 'NL05_02_049')      49
3718  ('GRQA', 'NL05_02_203')      49
3719  ('GRQA', 'NL05_02_302')      49
3721  ('GRQA', 'NL05_03_003')      49
3722  ('GRQA', 'NL05_03_022')      49
3726  ('GRQA', 'NL05_06_020')      49
3727  ('GRQA', 'NL05_06_024')      49
3728  ('GRQA', 'NL05_06_304')      49
3730  ('GRQA', 'NL05_07_301')      49
3732  ('GRQA', 'NL05_09_015')      49
3733  ('GRQA', 'NL05_10_002')      49
3736  ('GRQA', 'NL05_14_003')      49
3737  ('GRQA', 'NL05_14_004')      49
3738  ('GRQA', 'NL05_14_222')      49
3740  ('GRQA', 'NL05_15_016')      49
3741  ('GRQA', 'NL05_15_023')      49
3742  ('GRQA', 'NL05_15_026')      49
3744  ('GRQA', 'NL05_15_401')      49
3747  ('GRQA', 'NL05_16_005')      49
3748  ('GRQA', 'NL05_16_019')      49
3749  ('GRQA', 'NL05_16_020')      49
3752  ('GRQA', 'NL05_20_017')      49
3753  ('GRQA', 'NL05_20_020')      49
3755  ('GRQA', 'NL05_20_038')      49
3756  ('GRQA', 'NL05_20_074')      49
3757  ('GRQA', 'NL05_20_090')      49
3758  ('GRQA', 'NL05_20_092')      49
3759  ('GRQA', 'NL05_20_212')      49
3760  ('GRQA', 'NL05_20_215')      49
3762  ('GRQA', 'NL05_20_246')      49
3763  ('GRQA', 'NL05_20_401')      49
3765  ('GRQA', 'NL05_32_200')      49
3767  ('GRQA', 'NL05_34_001')      49
3768  ('GRQA', 'NL05_34_003')      49
3770  ('GRQA', 'NL05_34_305')      49
3772  ('GRQA', 'NL05_36_004')      49
3773  ('GRQA', 'NL05_36_200')      49
3775  ('GRQA', 'NL05_38_001')      49
3776  ('GRQA', 'NL05_39_002')      49
3777  ('GRQA', 'NL05_40_003')      49
3779  ('GRQA', 'NL05_40_009')      49
3781  ('GRQA', 'NL05_40_035')      49
3783  ('GRQA', 'NL05_40_220')      49

## 5. Read in again merged station data, but now assigned to stream id'S from HydroRivers shapefile:

In [18]:
# read in again station data with added information about closest river id in HydroRivers shapefile
# infromation can be found in columns NEAR_FID and the distance in NEAR_DIST 

stations = gpd.read_file('../../output_data/assign_stations_HydroRivers/ArcPy_output/stations_assigned_river.shp')
stations['SITE_id'] = stations['site_id']
stations['data_set'] = stations['dataset']
stations = stations.set_index(['dataset','site_id']).sort_index()


print(stations)

                               data_sourc country          area        lat  \
dataset site_id
GRQA    100001                    GLORICH     USA  2.120184e+10  47.160181
        100002                    GLORICH     USA  4.994408e+09  46.847909
        100003                    GLORICH     USA  5.949347e+09  46.773619
        100004                    GLORICH     USA  3.782731e+09  45.168718
        100005                    GLORICH     USA  5.736990e+08  44.606084
...                                   ...     ...           ...        ...
sweden  64       https://data.krycklan.se  sweden -9.999000e+03  64.162568
        65       https://data.krycklan.se  sweden -9.999000e+03  64.175916
        66       https://data.krycklan.se  sweden -9.999000e+03  64.172863
        7        https://data.krycklan.se  sweden -9.999000e+03  64.251301
        9        https://data.krycklan.se  sweden -9.999000e+03  64.237528

                       lon  NEAR_FID    NEAR_DIST                    geometry  \
dataset site_id
GRQA    100001  -67.927361   7384754    26.230632  POINT (-67.92736 47.16018)
        100002  -68.002459   7396181    28.635691  POINT (-68.00246 46.84791)
        100003  -67.831939   7398300     0.795138  POINT (-67.83194 46.77362)
        100004  -67.298037   7453269    10.131314  POINT (-67.29804 45.16872)
        100005  -67.935542   7472631    20.962179  POINT (-67.93554 44.60608)
...                    ...       ...          ...                         ...
sweden  64       19.570199   1618006  3222.032732    POINT (19.5702 64.16257)
        65       19.570540   1618006  1895.913905   POINT (19.57054 64.17592)
        66       19.862788   1618649   639.563847   POINT (19.86279 64.17286)
        7        19.777900   1616828  2235.286633     POINT (19.7779 64.2513)
        9        19.791562   1616828   760.749662   POINT (19.79156 64.23753)

                SITE_id data_set
dataset site_id
GRQA    100001   100001     GRQA
        100002   100002     GRQA
        100003   100003     GRQA
        100004   100004     GRQA
        100005   100005     GRQA
...                 ...      ...
sweden  64           64   sweden
        65           65   sweden
        66           66   sweden
        7             7   sweden
        9             9   sweden

[73924 rows x 10 columns]

## 6. Merge pairs of potential duplicated stations and stations dataset containing infos about countries, dataset, assigned river_id

In [19]:
###add criteria, in order to check whether station coordinates, country, river id (HydroRivers) and dataset are same or different 

######################################################################################################

# next step: Add information to extracted data table

# modify  station data:
station_2 = stations.copy()
station_2['station_id'] = station_2.index
station_2['station_id'] =station_2['station_id'].astype(str)
station_2 = station_2.reset_index()


merged_data = pairs_pot_duplicated.merge(station_2[['station_id', 'data_sourc', 'country', 'area', 'lat', 'lon', 'NEAR_FID', 'NEAR_DIST']], left_on='x', right_on='station_id', how='left')

# add prefix x_ to column names:
new_column_names_x = merged_data.columns[:3].tolist() + ['x_' + col for col in merged_data.columns[3:]]
merged_data.columns = new_column_names_x
print(merged_data)

# add data of y stations to dataframe:
all_pairs_dup = merged_data.merge(station_2[['station_id', 'data_sourc', 'country', 'area', 'lat', 'lon', 'NEAR_FID', 'NEAR_DIST']], left_on='y', right_on='station_id', how='left')

# add prefix y_ to column names:
cols_renamey = 8
new_column_names_y = all_pairs_dup.columns[:-cols_renamey].tolist() + ['y_' + col for col in all_pairs_dup.columns[-cols_renamey:]]
all_pairs_dup.columns = new_column_names_y
all_pairs_dup

                        x                          y distance_km  \
0      ('GRQA', '100002')  ('GRQA', 'USGS-01017100')       0.147
1      ('GRQA', '100003')  ('GRQA', 'USGS-01017500')       0.036
2      ('GRQA', '100004')         ('GRQA', '110876')      0.0124
3      ('GRQA', '100004')         ('GRQA', '110877')      0.0124
4      ('GRQA', '100004')       ('GRQA', 'CAN00052')      0.1286
...                   ...                        ...         ...
15060     ('sweden', '2')            ('sweden', '7')      0.0146
15061    ('sweden', '58')           ('sweden', '59')       0.227
15062     ('sweden', '6')            ('sweden', '7')      0.2327
15063    ('sweden', '60')           ('sweden', '66')      0.1613
15064    ('sweden', '61')           ('sweden', '62')      0.1192

             x_station_id              x_data_sourc x_country        x_area  \
0      ('GRQA', '100002')                   GLORICH       USA  4.994408e+09
1      ('GRQA', '100003')                   GLORICH       USA  5.949347e+09
2      ('GRQA', '100004')                   GLORICH       USA  3.782731e+09
3      ('GRQA', '100004')                   GLORICH       USA  3.782731e+09
4      ('GRQA', '100004')                   GLORICH       USA  3.782731e+09
...                   ...                       ...       ...           ...
15060     ('sweden', '2')  https://data.krycklan.se    sweden -9.999000e+03
15061    ('sweden', '58')  https://data.krycklan.se    sweden -9.999000e+03
15062     ('sweden', '6')  https://data.krycklan.se    sweden -9.999000e+03
15063    ('sweden', '60')  https://data.krycklan.se    sweden -9.999000e+03
15064    ('sweden', '61')  https://data.krycklan.se    sweden -9.999000e+03

           x_lat      x_lon  x_NEAR_FID  x_NEAR_DIST
0      46.847909 -68.002459     7396181    28.635691
1      46.773619 -67.831939     7398300     0.795138
2      45.168718 -67.298037     7453269    10.131314
3      45.168718 -67.298037     7453269    10.131314
4      45.168718 -67.298037     7453269    10.131314
...          ...        ...         ...          ...
15060  64.251425  19.777804     1616828  2249.110325
15061  64.179048  19.863411     1618649   462.150228
15062  64.250974  19.773143     1616828  2198.841702
15063  64.172828  19.866116     1618649   492.794143
15064  64.152538  19.550622     1620558  1975.943239

[15065 rows x 11 columns]

,x,y,distance_km,x_station_id,x_data_sourc,x_country,x_area,x_lat,x_lon,x_NEAR_FID,x_NEAR_DIST,y_station_id,y_data_sourc,y_country,y_area,y_lat,y_lon,y_NEAR_FID,y_NEAR_DIST
0,"('GRQA', '100002')","('GRQA', 'USGS-01017100')",0.147,"('GRQA', '100002')",GLORICH,USA,4.994408e+09,46.847909,-68.002459,7396181,28.635691,"('GRQA', 'USGS-01017100')",WQP,United States,1.943000e+03,46.849209,-68.002804,7396181,55.003173
1,"('GRQA', '100003')","('GRQA', 'USGS-01017500')",0.036,"('GRQA', '100003')",GLORICH,USA,5.949347e+09,46.773619,-67.831939,7398300,0.795138,"('GRQA', 'USGS-01017500')",WQP,United States,2.301000e+03,46.773372,-67.831633,7398300,4.542234
2,"('GRQA', '100004')","('GRQA', '110876')",0.0124,"('GRQA', '100004')",GLORICH,USA,3.782731e+09,45.168718,-67.298037,7453269,10.131314,"('GRQA', '110876')",GLORICH,Canada,3.782731e+09,45.168609,-67.298070,7453269,18.885529
3,"('GRQA', '100004')","('GRQA', '110877')",0.0124,"('GRQA', '100004')",GLORICH,USA,3.782731e+09,45.168718,-67.298037,7453269,10.131314,"('GRQA', '110877')",GLORICH,Canada,3.782731e+09,45.168609,-67.298070,7453269,18.885529
4,"('GRQA', '100004')","('GRQA', 'CAN00052')",0.1286,"('GRQA', '100004')",GLORICH,USA,3.782731e+09,45.168718,-67.298037,7453269,10.131314,"('GRQA', 'CAN00052')",GEMSTAT,Canada,-9.999000e+03,45.169720,-67.297220,7453269,17.538434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15060,"('sweden', '2')","('sweden', '7')",0.0146,"('sweden', '2')",https://data.krycklan.se,sweden,-9.999000e+03,64.251425,19.777804,1616828,2249.110325,"('sweden', '7')",https://data.krycklan.se,sweden,-9.999000e+03,64.251301,19.777900,1616828,2235.286633
15061,"('sweden', '58')","('sweden', '59')",0.227,"('sweden', '58')",https://data.krycklan.se,sweden,-9.999000e+03,64.179048,19.863411,1618649,462.150228,"('sweden', '59')",https://data.krycklan.se,sweden,-9.999000e+03,64.177068,19.864548,1618649,406.903617
15062,"('sweden', '6')","('sweden', '7')",0.2327,"('sweden', '6')",https://data.krycklan.se,sweden,-9.999000e+03,64.250974,19.773143,1616828,2198.841702,"('sweden', '7')",https://data.krycklan.se,sweden,-9.999000e+03,64.251301,19.777900,1616828,2235.286633
15063,"('sweden', '60')","('sweden', '66')",0.1613,"('sweden', '60')",https://data.krycklan.se,sweden,-9.999000e+03,64.172828,19.866116,1618649,492.794143,"('sweden', '66')",https://data.krycklan.se,sweden,-9.999000e+03,64.172863,19.862788,1618649,639.563847
15064,"('sweden', '61')","('sweden', '62')",0.1192,"('sweden', '61')",https://data.krycklan.se,sweden,-9.999000e+03,64.152538,19.550622,1620558,1975.943239,"('sweden', '62')",https://data.krycklan.se,sweden,-9.999000e+03,64.152279,19.548236,1620558,1876.709382

In [20]:
# add country code: if both from same country yes else no
# in dataset occure some aliases: for example: PL and poland or NL and Netherlands

# Define a dictionary of country aliases
country_aliases = {
    'Poland': ['PL'],
    'USA': ['US', 'United States', 'United States of America (the)'],
    'Sweden': ['SE', 'sweden', 'SWEDEN'],
    'Netherlands':['NL', 'Netherlands (the)'],
    'Austria':['AT'],
    'Switzerland':['CH'],
    'South Africa':['RSA'],
    'Croatia':['HR'],
    'UK': ['United Kingdom of Great Britain and Northern Ireland (the)'],
    'Macedonia (the former Yugoslav Republic of)':['MK']
}

# Function to replace values based on aliases
def replace_with_alias(value):
    for country, aliases in country_aliases.items():
        if value in aliases:
            return country
    return value

# Apply the replacement function to columns 'x' and 'y'
all_pairs_dup['x_country'] = all_pairs_dup['x_country'].apply(replace_with_alias)
all_pairs_dup['y_country'] = all_pairs_dup['y_country'].apply(replace_with_alias)

# add column 'same country' to dataframe: if both stations are from same country add True else False
all_pairs_dup['same_country'] = np.where(all_pairs_dup['x_country']==all_pairs_dup['y_country'],True, False)
print(all_pairs_dup[all_pairs_dup['same_country']==False])
diff_country  =all_pairs_dup[all_pairs_dup['same_country']==False]

# save file containing list of pot_duplicated stations origin from different countries
diff_country.to_csv(f'../../output_data/merge_0km_dist_stations/diff_country_code_{thrs}_km.csv')

diff_country

# add dataset
# add observed compounds for x and y --> überlappung pder ergänzend

                               x                             y distance_km  \
2             ('GRQA', '100004')            ('GRQA', '110876')      0.0124
3             ('GRQA', '100004')            ('GRQA', '110877')      0.0124
4             ('GRQA', '100004')          ('GRQA', 'CAN00052')      0.1286
5             ('GRQA', '100004')          ('GRQA', 'CAN00200')      0.2014
1499          ('GRQA', '102516')          ('GRQA', 'MEX03538')      0.1939
1500          ('GRQA', '102516')          ('GRQA', 'MEX03539')      0.1906
1613          ('GRQA', '102703')            ('GRQA', '110088')      0.0112
2286          ('GRQA', '110047')     ('GRQA', 'USGS-12211900')      0.0924
2292          ('GRQA', '110088')          ('USGS', '12355000')      0.1855
2305          ('GRQA', '110685')     ('GRQA', 'USGS-01014000')      0.2216
2310          ('GRQA', '110694')     ('GRQA', 'USGS-01014000')      0.2216
2312          ('GRQA', '110695')     ('GRQA', 'USGS-01014000')      0.2216
2313          ('GRQA', '110696')     ('GRQA', 'USGS-01014000')      0.2216
2363          ('GRQA', '110876')     ('GRQA', 'USGS-01021050')      0.1898
2364          ('GRQA', '110876')     ('GRQA', 'USGS-01021051')      0.1723
2367          ('GRQA', '110877')     ('GRQA', 'USGS-01021050')      0.1898
2368          ('GRQA', '110877')     ('GRQA', 'USGS-01021051')      0.1723
2635          ('GRQA', '120049')        ('GRQA', 'AL07AA0015')      0.2243
2636          ('GRQA', '120049')          ('GRQA', 'CAN00181')       0.224
2637          ('GRQA', '200073')            ('GRQA', '201881')      0.0766
2644          ('GRQA', '201840')          ('GRQA', 'PER00011')      0.1615
2645          ('GRQA', '201842')          ('GRQA', 'PER00012')      0.0958
2646          ('GRQA', '201875')          ('GRQA', 'BOL00003')      0.2322
2647          ('GRQA', '201891')          ('GRQA', 'BRA00122')      0.1561
2669          ('GRQA', '301513')          ('GRQA', 'FRA00034')       0.219
2765          ('GRQA', '310167')         ('GRQA', 'CHRW-1514')      0.1574
2788          ('GRQA', '310471')         ('GRQA', 'CHRW-1838')      0.0119
2979          ('GRQA', '313128')    ('GRQA', 'PL02S1401_1374')      0.1995
3191          ('GRQA', '410205')          ('GRQA', 'SDN00002')      0.2318
3339    ('GRQA', 'ATFW40502017')       ('germany', 'BY_12872')      0.0199
3340    ('GRQA', 'ATFW40607017')       ('germany', 'BY_13306')      0.0079
3405        ('GRQA', 'CAN00052')     ('GRQA', 'USGS-01021050')      0.0534
3406        ('GRQA', 'CAN00052')     ('GRQA', 'USGS-01021051')      0.0448
3588         ('GRQA', 'HR29160')          ('GRQA', 'SVN00001')       0.031
3670        ('GRQA', 'MEX03513')     ('GRQA', 'USGS-09534000')      0.1098
3672        ('GRQA', 'MEX03539')     ('GRQA', 'USGS-10254970')      0.0213
4974   ('GRQA', 'NL36_OWM_014M')    ('germany', 'NI_92862534')      0.0312
4987        ('GRQA', 'NLD00112')    ('germany', 'NI_92862534')      0.0312
5043  ('GRQA', 'PL02S1401_1374')    ('germany', 'SN_OBF16800')       0.198
5044  ('GRQA', 'PL02S1401_1374')  ('germany', 'SN_OBF16800_m')       0.198
5046  ('GRQA', 'PL02S1401_1378')    ('germany', 'SN_OBF17500')        0.19
5047  ('GRQA', 'PL02S1401_3225')    ('germany', 'SN_OBF17290')      0.0884
5049        ('GRQA', 'POL00026')    ('germany', 'SN_OBF17500')        0.19

                    x_station_id x_data_sourc    x_country        x_area  \
2             ('GRQA', '100004')      GLORICH          USA  3.782731e+09
3             ('GRQA', '100004')      GLORICH          USA  3.782731e+09
4             ('GRQA', '100004')      GLORICH          USA  3.782731e+09
5             ('GRQA', '100004')      GLORICH          USA  3.782731e+09
1499          ('GRQA', '102516')      GLORICH          USA  7.431277e+08
1500          ('GRQA', '102516')      GLORICH          USA  7.431277e+08
1613          ('GRQA', '102703')      GLORICH          USA  1.124404e+09
2286          ('GRQA', '110047')      GLORICH       Canada  3.681149e+07
2292          ('GRQA', '110088')      GLORICH       Canada  1.124404e+09
2305          ('GRQA', '110685')      GLORICH       Canada  1.477333e+10
2310          ('GRQA', '110694')      GLORICH       Canada  1.477333e+10
2312          ('GRQA', '110695')      GLORICH       Canada  1.477333e+10
2313          ('GRQA', '110696')      GLORICH       Canada  1.477333e+10
2363          ('GRQA', '110876')      GLORICH       Canada  3.782731e+09
2364          ('GRQA', '110876')      GLORICH       Canada  3.782731e+09
2367          ('GRQA', '110877')      GLORICH       Canada  3.782731e+09
2368          ('GRQA', '110877')      GLORICH       Canada  3.782731e+09
2635          ('GRQA', '120049')      GLORICH        -9999  2.416410e+09
2636          ('GRQA', '120049')      GLORICH        -9999  2.416410e+09
2637          ('GRQA', '200073')      GLORICH       Brazil  9.253842e+11
2644          ('GRQA', '201840')      GLORICH        -9999  1.148986e+11
2645          ('GRQA', '201842')      GLORICH        -9999  1.922347e+11
2646          ('GRQA', '201875')      GLORICH        -9999  7.037069e+10
2647          ('GRQA', '201891')      GLORICH        -9999  1.317755e+12
2669          ('GRQA', '301513')      GLORICH      Germany  4.581233e+10
2765          ('GRQA', '310167')      GLORICH       France  2.145809e+08
2788          ('GRQA', '310471')      GLORICH       France  1.034763e+10
2979          ('GRQA', '313128')      GLORICH      Germany  3.665243e+08
3191          ('GRQA', '410205')      GLORICH        Sudan  1.672493e+12
3339    ('GRQA', 'ATFW40502017')    WATERBASE      Austria -9.999000e+03
3340    ('GRQA', 'ATFW40607017')    WATERBASE      Austria -9.999000e+03
3405        ('GRQA', 'CAN00052')      GEMSTAT       Canada -9.999000e+03
3406        ('GRQA', 'CAN00052')      GEMSTAT       Canada -9.999000e+03
3588         ('GRQA', 'HR29160')    WATERBASE      Croatia -9.999000e+03
3670        ('GRQA', 'MEX03513')      GEMSTAT       Mexico -9.999000e+03
3672        ('GRQA', 'MEX03539')      GEMSTAT       Mexico -9.999000e+03
4974   ('GRQA', 'NL36_OWM_014M')    WATERBASE  Netherlands -9.999000e+03
4987        ('GRQA', 'NLD00112')      GEMSTAT  Netherlands -9.999000e+03
5043  ('GRQA', 'PL02S1401_1374')    WATERBASE       Poland -9.999000e+03
5044  ('GRQA', 'PL02S1401_1374')    WATERBASE       Poland -9.999000e+03
5046  ('GRQA', 'PL02S1401_1378')    WATERBASE       Poland -9.999000e+03
5047  ('GRQA', 'PL02S1401_3225')    WATERBASE       Poland -9.999000e+03
5049        ('GRQA', 'POL00026')      GEMSTAT       Poland -9.999000e+03

          x_lat       x_lon  x_NEAR_FID   x_NEAR_DIST  \
2     45.168718  -67.298037     7453269     10.131314
3     45.168718  -67.298037     7453269     10.131314
4     45.168718  -67.298037     7453269     10.131314
5     45.168718  -67.298037     7453269     10.131314
1499  32.664588 -115.502095     7780241      0.478397
1500  32.664588 -115.502095     7780241      0.478397
1613  49.002090 -114.477097     7319028      0.433733
2286  49.002305 -122.406209     7319893     10.898800
2292  49.002182 -114.477036     7319028      8.958717
2305  47.281342  -68.585362     7380508      2.344931
2310  47.281342  -68.585362     7380508      2.344931
2312  47.281342  -68.585362     7380508      2.344931
2313  47.281342  -68.585362     7380508      2.344931
2363  45.168609  -67.298070     7453269     18.885529
2364  45.168609  -67.298070     7453269     18.885529
2367  45.168609  -67.298070     7453269     18.885529
2368  45.168609  -67.298070     7453269     18.885529
2635  52.665125 -117.877703     7198677  23835.346690
2636  52.665125 -117.877703     7198677  23835.346690
2637  -9.705744  -65.368287     6399707     75.572886
2644  -4.468838  -77.548250     6104627      9.747024
2645 -10.677248  -73.817900     6444989     18.237605
2646 -14.443792  -67.535657     6584865     26.319826
2647  -4.897793  -60.026422     6131236     42.099521
2669  48.682254    7.914723     1934432     53.031022
2765  47.502229    7.010656     1968823     23.982996
2788  46.144684    5.965091     2004757     27.039706
2979  50.872549   14.823388     1880344     33.145930
3191  15.501753   32.464502      445475     19.183229
3339  48.261020   13.034350     1945982     67.080066
3340  48.520660   13.702220     1939792    125.921796
3405  45.169720  -67.297220     7453269     17.538434
3406  45.169720  -67.297220     7453269     17.538434
3588  46.402820   16.154850     1998099     81.885386
3670  32.487501 -114.790833     7784091   1135.181743
3672  32.666080 -115.503097     7780241     34.582157
4974  52.611600    6.738890     1836050    132.507917
4987  52.611600    6.738890     1836050    132.507917
5043  50.870800   14.822760     1880344     11.028151
5044  50.870800   14.822760     1880344     11.028151
5046  51.257360   15.031770     1869845    281.246190
5047  51.061090   14.966210     1874509     56.553960
5049  51.257360   15.031770     1869845    281.246190

                      y_station_id y_data_sourc  \
2               ('GRQA', '110876')      GLORICH
3               ('GRQA', '110877')      GLORICH
4             ('GRQA', 'CAN00052')      GEMSTAT
5             ('GRQA', 'CAN00200')      GEMSTAT
1499          ('GRQA', 'MEX03538')      GEMSTAT
1500          ('GRQA', 'MEX03539')      GEMSTAT
1613            ('GRQA', '110088')      GLORICH
2286     ('GRQA', 'USGS-12211900')          WQP
2292          ('USGS', '12355000')         USGS
2305     ('GRQA', 'USGS-01014000')          WQP
2310     ('GRQA', 'USGS-01014000')          WQP
2312     ('GRQA', 'USGS-01014000')          WQP
2313     ('GRQA', 'USGS-01014000')          WQP
2363     ('GRQA', 'USGS-01021050')          WQP
2364     ('GRQA', 'USGS-01021051')          WQP
2367     ('GRQA', 'USGS-01021050')          WQP
2368     ('GRQA', 'USGS-01021051')          WQP
2635        ('GRQA', 'AL07AA0015')         CESI
2636          ('GRQA', 'CAN00181')      GEMSTAT
2637            ('GRQA', '201881')      GLORICH
2644          ('GRQA', 'PER00011')      GEMSTAT
2645          ('GRQA', 'PER00012')      GEMSTAT
2646          ('GRQA', 'BOL00003')      GEMSTAT
2647          ('GRQA', 'BRA00122')      GEMSTAT
2669          ('GRQA', 'FRA00034')      GEMSTAT
2765         ('GRQA', 'CHRW-1514')    WATERBASE
2788         ('GRQA', 'CHRW-1838')    WATERBASE
2979    ('GRQA', 'PL02S1401_1374')    WATERBASE
3191          ('GRQA', 'SDN00002')      GEMSTAT
3339       ('germany', 'BY_12872')         GDS1
3340       ('germany', 'BY_13306')         GDS1
3405     ('GRQA', 'USGS-01021050')          WQP
3406     ('GRQA', 'USGS-01021051')          WQP
3588          ('GRQA', 'SVN00001')      GEMSTAT
3670     ('GRQA', 'USGS-09534000')          WQP
3672     ('GRQA', 'USGS-10254970')          WQP
4974    ('germany', 'NI_92862534')         GDS2
4987    ('germany', 'NI_92862534')         GDS2
5043    ('germany', 'SN_OBF16800')         GDS1
5044  ('germany', 'SN_OBF16800_m')         GDS1
5046    ('germany', 'SN_OBF17500')         GDS1
5047    ('germany', 'SN_OBF17290')         GDS1
5049    ('germany', 'SN_OBF17500')         GDS1

                             y_country        y_area      y_lat       y_lon  \
2                               Canada  3.782731e+09  45.168609  -67.298070
3                               Canada  3.782731e+09  45.168609  -67.298070
4                               Canada -9.999000e+03  45.169720  -67.297220
5                               Canada -9.999000e+03  45.168600  -67.300600
1499                            Mexico -9.999000e+03  32.664502 -115.500027
1500                            Mexico -9.999000e+03  32.666080 -115.503097
1613                            Canada  1.124404e+09  49.002182 -114.477036
2286                               USA -9.999000e+03  49.002618 -122.407382
2292                               USA  1.117890e+03  49.000529 -114.477371
2305                               USA  5.929000e+03  47.283333  -68.585278
2310                               USA  5.929000e+03  47.283333  -68.585278
2312                               USA  5.929000e+03  47.283333  -68.585278
2313                               USA  5.929000e+03  47.283333  -68.585278
2363                               USA  1.455000e+03  45.170000  -67.296667
2364                               USA  1.460000e+03  45.169797  -67.296659
2367                               USA  1.455000e+03  45.170000  -67.296667
2368                               USA  1.460000e+03  45.169797  -67.296659
2635                            Canada -9.999000e+03  52.664440 -117.880830
2636                            Canada -9.999000e+03  52.664400 -117.880800
2637                             -9999  9.253842e+11  -9.706221  -65.368791
2644                              Peru  1.172000e+05  -4.470277  -77.548055
2645                              Peru  1.955300e+05 -10.678100  -73.817770
2646  Bolivia (Plurinational State of)  6.890000e+04 -14.445300  -67.534166
2647                            Brazil  1.324700e+06  -4.896944  -60.025300
2669                            France -9.999000e+03  48.683850    7.916470
2765                       Switzerland -9.999000e+03  47.501670    7.012580
2788                       Switzerland -9.999000e+03  46.144580    5.965130
2979                            Poland -9.999000e+03  50.870800   14.822760
3191                       Sudan (the)  8.552000e+04  15.500000   32.463333
3339                           Germany  2.278220e+04  48.260969   13.034092
3340                           Germany  7.709920e+04  48.520707   13.702140
3405                               USA  1.455000e+03  45.170000  -67.296667
3406                               USA  1.460000e+03  45.169797  -67.296659
3588                          Slovenia -9.999000e+03  46.403070   16.155030
3670                               USA -9.999000e+03  32.487583 -114.789667
3672                               USA -9.999000e+03  32.665892 -115.503050
4974                           Germany -9.999000e+03  52.611606    6.738428
4987                           Germany -9.999000e+03  52.611606    6.738428
5043                           Germany -9.999000e+03  50.872211   14.821041
5044                           Germany  3.697200e+02  50.872211   14.821041
5046                           Germany  1.791500e+03  51.255988   15.030143
5047                           Germany -9.999000e+03  51.060354   14.965733
5049                           Germany  1.791500e+03  51.255988   15.030143

      y_NEAR_FID   y_NEAR_DIST  same_country
2        7453269     18.885529         False
3        7453269     18.885529         False
4        7453269     17.538434         False
5        7453269    211.608309         False
1499     7780241      9.021653         False
1500     7780241     34.582157         False
1613     7319028      8.958717         False
2286     7319893    101.718721         False
2292     7319483    112.599523         False
2305     7380507     10.507193         False
2310     7380507     10.507193         False
2312     7380507     10.507193         False
2313     7380507     10.507193         False
2363     7453269      0.002990         False
2364     7453269     13.509925         False
2367     7453269      0.002990         False
2368     7453269     13.509925         False
2635     7198677  23695.127586         False
2636     7198677  23691.552876         False
2637     6399707      3.205832         False
2644     6105416     15.352663         False
2645     6444989    112.455395         False
2646     6584865     23.112584         False
2647     6131236     63.514927         False
2669     1934432     43.766509         False
2765     1968823    109.123538         False
2788     2004757     17.971384         False
2979     1880344     11.028151         False
3191      445475     64.199228         False
3339     1945982     61.373352         False
3340     1939792    123.933057         False
3405     7453269      0.002990         False
3406     7453269     13.509925         False
3588     1998099    109.675318         False
3670     7784091   1045.658943         False
3672     7780241     24.513350         False
4974     1836050    105.405805         False
4987     1836050    105.405805         False
5043     1880344    132.044468         False
5044     1880344    132.044468         False
5046     1869845    296.337646         False
5047     1874509     71.885602         False
5049     1869845    296.337646         False

,x,y,distance_km,x_station_id,x_data_sourc,x_country,x_area,x_lat,x_lon,x_NEAR_FID,x_NEAR_DIST,y_station_id,y_data_sourc,y_country,y_area,y_lat,y_lon,y_NEAR_FID,y_NEAR_DIST,same_country
2,"('GRQA', '100004')","('GRQA', '110876')",0.0124,"('GRQA', '100004')",GLORICH,USA,3.782731e+09,45.168718,-67.298037,7453269,10.131314,"('GRQA', '110876')",GLORICH,Canada,3.782731e+09,45.168609,-67.298070,7453269,18.885529,False
3,"('GRQA', '100004')","('GRQA', '110877')",0.0124,"('GRQA', '100004')",GLORICH,USA,3.782731e+09,45.168718,-67.298037,7453269,10.131314,"('GRQA', '110877')",GLORICH,Canada,3.782731e+09,45.168609,-67.298070,7453269,18.885529,False
4,"('GRQA', '100004')","('GRQA', 'CAN00052')",0.1286,"('GRQA', '100004')",GLORICH,USA,3.782731e+09,45.168718,-67.298037,7453269,10.131314,"('GRQA', 'CAN00052')",GEMSTAT,Canada,-9.999000e+03,45.169720,-67.297220,7453269,17.538434,False
5,"('GRQA', '100004')","('GRQA', 'CAN00200')",0.2014,"('GRQA', '100004')",GLORICH,USA,3.782731e+09,45.168718,-67.298037,7453269,10.131314,"('GRQA', 'CAN00200')",GEMSTAT,Canada,-9.999000e+03,45.168600,-67.300600,7453269,211.608309,False
1499,"('GRQA', '102516')","('GRQA', 'MEX03538')",0.1939,"('GRQA', '102516')",GLORICH,USA,7.431277e+08,32.664588,-115.502095,7780241,0.478397,"('GRQA', 'MEX03538')",GEMSTAT,Mexico,-9.999000e+03,32.664502,-115.500027,7780241,9.021653,False
1500,"('GRQA', '102516')","('GRQA', 'MEX03539')",0.1906,"('GRQA', '102516')",GLORICH,USA,7.431277e+08,32.664588,-115.502095,7780241,0.478397,"('GRQA', 'MEX03539')",GEMSTAT,Mexico,-9.999000e+03,32.666080,-115.503097,7780241,34.582157,False
1613,"('GRQA', '102703')","('GRQA', '110088')",0.0112,"('GRQA', '102703')",GLORICH,USA,1.124404e+09,49.002090,-114.477097,7319028,0.433733,"('GRQA', '110088')",GLORICH,Canada,1.124404e+09,49.002182,-114.477036,7319028,8.958717,False
2286,"('GRQA', '110047')","('GRQA', 'USGS-12211900')",0.0924,"('GRQA', '110047')",GLORICH,Canada,3.681149e+07,49.002305,-122.406209,7319893,10.898800,"('GRQA', 'USGS-12211900')",WQP,USA,-9.999000e+03,49.002618,-122.407382,7319893,101.718721,False
2292,"('GRQA', '110088')","('USGS', '12355000')",0.1855,"('GRQA', '110088')",GLORICH,Canada,1.124404e+09,49.002182,-114.477036,7319028,8.958717,"('USGS', '12355000')",USGS,USA,1.117890e+03,49.000529,-114.477371,7319483,112.599523,False
2305,"('GRQA', '110685')","('GRQA', 'USGS-01014000')",0.2216,"('GRQA', '110685')",GLORICH,Canada,1.477333e+10,47.281342,-68.585362,7380508,2.344931,"('GRQA', 'USGS-01014000')",WQP,USA,5.929000e+03,47.283333,-68.585278,7380507,10.507193,False
2310,"('GRQA', '110694')","('GRQA', 'USGS-01014000')",0.2216,"('GRQA', '110694')",GLORICH,Canada,1.477333e+10,47.281342,-68.585362,7380508,2.344931,"('GRQA', 'USGS-01014000')",WQP,USA,5.929000e+03,47.283333,-68.585278,7380507,10.507193,False
2312,"('GRQA', '110695')","('GRQA', 'USGS-01014000')",0.2216,"('GRQA', '110695')",GLORICH,Canada,1.477333e+10,47.281342,-68.585362,7380508,2.344931,"('GRQA', 'USGS-01014000')",WQP,USA,5.929000e+03,47.283333,-68.585278,7380507,10.507193,False
2313,"('GRQA', '110696')","('GRQA', 'USGS-01014000')",0.2216,"('GRQA', '110696')",GLORICH,Canada,1.477333e+10,47.281342,-68.585362,7380508,2.344931,"('GRQA', 'USGS-01014000')",WQP,USA,5.929000e+03,47.283333,-68.585278,7380507,10.507193,False
2363,"('GRQA', '110876')","('GRQA', 'USGS-01021050')",0.1898,"('GRQA', '110876')",GLORICH,Canada,3.782731e+09,45.168609,-67.298070,7453269,18.885529,"('GRQA', 'USGS-01021050')",WQP,USA,1.455000e+03,45.170000,-67.296667,7453269,0.002990,False
2364,"('GRQA', '110876')","('GRQA', 'USGS-01021051')",0.1723,"('GRQA', '110876')",GLORICH,Canada,3.782731e+09,45.168609,-67.298070,7453269,18.885529,"('GRQA', 'USGS-01021051')",WQP,USA,1.460000e+03,45.169797,-67.296659,7453269,13.509925,False
2367,"('GRQA', '110877')","('GRQA', 'USGS-01021050')",0.1898,"('GRQA', '110877')",GLORICH,Canada,3.782731e+09,45.168609,-67.298070,7453269,18.885529,"('GRQA', 'USGS-01021050')",WQP,USA,1.455000e+03,45.170000,-67.296667,7453269,0.002990,False
2368,"('GRQA', '110877')","('GRQA', 'USGS-01021051')",0.1723,"('GRQA', '110877')",GLORICH,Canada,3.782731e+09,45.168609,-67.298070,7453269,18.885529,"('GRQA', 'USGS-01021051')",WQP,USA,1.460000e+03,45.169797,-67.296659,7453269,13.509925,False
2635,"('GRQA', '120049')","('GRQA', 'AL07AA0015')",0.2243,"('GRQA', '120049')",GLORICH,-9999,2.416410e+09,52.665125,-117.877703,7198677,23835.346690,"('GRQA', 'AL07AA0015')",CESI,Canada,-9.999000e+03,52.664440,-117.880830,7198677,23695.127586,False
2636,"('GRQA', '120049')","('GRQA', 'CAN00181')",0.224,"('GRQA', '120049')",GLORICH,-9999,2.416410e+09,52.665125,-117.877703,7198677,23835.346690,"('GRQA', 'CAN00181')",GEMSTAT,Canada,-9.999000e+03,52.664400,-117.880800,7198677,23691.552876,False
2637,"('GRQA', '200073')","('GRQA', '201881')",0.0766,"('GRQA', '200073')",GLORICH,Brazil,9.253842e+11,-9.705744,-65.368287,6399707,75.572886,"('GRQA', '201881')",GLORICH,-9999,9.253842e+11,-9.706221,-65.368791,6399707,3.205832,False
2644,"('GRQA', '201840')","('GRQA', 'PER00011')",0.1615,"('GRQA', '201840')",GLORICH,-9999,1.148986e+11,-4.468838,-77.548250,6104627,9.747024,"('GRQA', 'PER00011')",GEMSTAT,Peru,1.172000e+05,-4.470277,-77.548055,6105416,15.352663,False
2645,"('GRQA', '201842')","('GRQA', 'PER00012')",0.0958,"('GRQA', '201842')",GLORICH,-9999,1.922347e+11,-10.677248,-73.817900,6444989,18.237605,"('GRQA', 'PER00012')",GEMSTAT,Peru,1.955300e+05,-10.678100,-73.817770,6444989,112.455395,False
2646,"('GRQA', '201875')","('GRQA', 'BOL00003')",0.2322,"('GRQA', '201875')",GLORICH,-9999,7.037069e+10,-14.443792,-67.535657,6584865,26.319826,"('GRQA', 'BOL00003')",GEMSTAT,Bolivia (Plurinational State of),6.890000e+04,-14.445300,-67.534166,6584865,23.112584,False
2647,"('GRQA', '201891')","('GRQA', 'BRA00122')",0.1561,"('GRQA', '201891')",GLORICH,-9999,1.317755e+12,-4.897793,-60.026422,6131236,42.099521,"('GRQA', 'BRA00122')",GEMSTAT,Brazil,1.324700e+06,-4.896944,-60.025300,6131236,63.514927,False
2669,"('GRQA', '301513')","('GRQA', 'FRA00034')",0.219,"('GRQA', '301513')",GLORICH,Germany,4.581233e+10,48.682254,7.914723,1934432,53.031022,"('GRQA', 'FRA00034')",GEMSTAT,France,-9.999000e+03,48.683850,7.916470,1934432,43.766509,False
2765,"('GRQA', '310167')","('GRQA', 'CHRW-1514')",0.1574,"('GRQA', '310167')",GLORICH,France,2.145809e+08,47.502229,7.010656,1968823,23.982996,"('GRQA', 'CHRW-1514')",WATERBASE,Switzerland,-9.999000e+03,47.501670,7.012580,1968823,109.123538,False
2788,"('GRQA', '310471')","('GRQA', 'CHRW-1838')",0.0119,"('GRQA', '310471')",GLORICH,France,1.034763e+10,46.144684,5.965091,2004757,27.039706,"('GRQA', 'CHRW-1838')",WATERBASE,Switzerland,-9.999000e+03,46.144580,5.965130,2004757,17.971384,False
2979,"('GRQA', '313128')","('GRQA', 'PL02S1401_1374')",0.1995,"('GRQA', '313128')",GLORICH,Germany,3.665243e+08,50.872549,14.823388,1880344,33.145930,"('GRQA', 'PL02S1401_1374')",WATERBASE,Poland,-9.999000e+03,50.870800,14.822760,1880344,11.028151,False
3191,"('GRQA', '410205')","('GRQA', 'SDN00002')",0.2318,"('GRQA', '410205')",GLORICH,Sudan,1.672493e+12,15.501753,32.464502,445475,19.183229,"('GRQA', 'SDN00002')",GEMSTAT,Sudan (the),8.552000e+04,15.500000,32.463333,445475,64.199228,False
3339,"('GRQA', 'ATFW40502017')","('germany', 'BY_12872')",0.0199,"('GRQA', 'ATFW40502017')",WATERBASE,Austria,-9.999000e+03,48.261020,13.034350,1945982,67.080066,"('germany', 'BY_12872')",GDS1,Germany,2.278220e+04,48.260969,13.034092,1945982,61.373352,False
3340,"('GRQA', 'ATFW40607017')","('germany', 'BY_13306')",0.0079,"('GRQA', 'ATFW40607017')",WATERBASE,Austria,-9.999000e+03,48.520660,13.702220,1939792,125.921796,"('germany', 'BY_13306')",GDS1,Germany,7.709920e+04,48.520707,13.702140,1939792,123.933057,False
3405,"('GRQA', 'CAN00052')","('GRQA', 'USGS-01021050')",0.0534,"('GRQA', 'CAN00052')",GEMSTAT,Canada,-9.999000e+03,45.169720,-67.297220,7453269,17.538434,"('GRQA', 'USGS-01021050')",WQP,USA,1.455000e+03,45.170000,-67.296667,7453269,0.002990,False
3406,"('GRQA', 'CAN00052')","('GRQA', 'USGS-01021051')",0.0448,"('GRQA', 'CAN00052')",GEMSTAT,Canada,-9.999000e+03,45.169720,-67.297220,7453269,17.538434,"('GRQA', 'USGS-01021051')",WQP,USA,1.460000e+03,45.169797,-67.296659,7453269,13.509925,False
3588,"('GRQA', 'HR29160')","('GRQA', 'SVN00001')",0.031,"('GRQA', 'HR29160')",WATERBASE,Croatia,-9.999000e+03,46.402820,16.154850,1998099,81.885386,"('GRQA', 'SVN00001')",GEMSTAT,Slovenia,-9.999000e+03,46.403070,16.155030,1998099,109.675318,False
3670,"('GRQA', 'MEX03513')","('GRQA', 'USGS-09534000')",0.1098,"('GRQA', 'MEX03513')",GEMSTAT,Mexico,-9.999000e+03,32.487501,-114.790833,7784091,1135.181743,"('GRQA', 'USGS-09534000')",WQP,USA,-9.999000e+03,32.487583,-114.789667,7784091,1045.658943,False
3672,"('GRQA', 'MEX03539')","('GRQA', 'USGS-10254970')",0.0213,"('GRQA', 'MEX03539')",GEMSTAT,Mexico,-9.999000e+03,32.666080,-115.503097,7780241,34.582157,"('GRQA', 'USGS-10254970')",WQP,USA,-9.999000e+03,32.665892,-115.503050,7780241,24.513350,False
4974,"('GRQA', 'NL36_OWM_014M')","('germany', 'NI_92862534')",0.0312,"('GRQA', 'NL36_OWM_014M')",WATERBASE,Netherlands,-9.999000e+03,52.611600,6.738890,1836050,132.507917,"('germany', 'NI_92862534')",GDS2,Germany,-9.999000e+03,52.611606,6.738428,1836050,105.405805,False
4987,"('GRQA', 'NLD00112')","('germany', 'NI_92862534')",0.0312,"('GRQA', 'NLD00112')",GEMSTAT,Netherlands,-9.999000e+03,52.611600,6.738890,1836050,132.507917,"('germany', 'NI_92862534')",GDS2,Germany,-9.999000e+03,52.611606,6.738428,1836050,105.405805,False
5043,"('GRQA', 'PL02S1401_1374')","('germany', 'SN_OBF16800')",0.198,"('GRQA', 'PL02S1401_1374')",WATERBASE,Poland,-9.999000e+03,50.870800,14.822760,1880344,11.028151,"('germany', 'SN_OBF16800')",GDS1,Germany,-9.999000e+03,50.872211,14.821041,1880344,132.044468,False
5044,"('GRQA', 'PL02S1401_1374')","('germany', 'SN_OBF16800_m')",0.198,"('GRQA', 'PL02S1401_1374')",WATERBASE,Poland,-9.999000e+03,50.870800,14.822760,1880344,11.028151,"('germany', 'SN_OBF16800_m')",GDS1,Germany,3.697200e+02,50.872211,14.821041,1880344,132.044468,False
5046,"('GRQA', 'PL02S1401_1378')","('germany', 'SN_OBF17500')",0.19,"('GRQA', 'PL02S1401_1378')",WATERBASE,Poland,-9.999000e+03,51.257360,15.031770,1869845,281.246190,"('germany', 'SN_OBF17500')",GDS1,Germany,1.791500e+03,51.255988,15.030143,1869845,296.337646,False
5047,"('GRQA', 'PL02S1401_3225')","('germany', 'SN_OBF17290')",0.0884,"('GRQA', 'PL02S1401_3225')",WATERBASE,Poland,-9.999000e+03,51.061090,14.966210,1874509,56.553960,"('germany', 'SN_OBF17290')",GDS1,Germany,-9.999000e+03,51.060354,14.965733,1874509,71.885602,False
5049,"('GRQA', 'POL00026')","('germany', 'SN_OBF17500')",0.19,"('GRQA', 'POL00026')",GEMSTAT,Poland,-9.999000e+03,51.257360,15.031770,1869845,281.246190,"('germany', 'SN_OBF17500')",GDS1,Germany,1.791500e+03,51.255988,15.030143,1869845,296.337646,False

In [21]:
# add column 'same_river_id' to dataframe: if both stations are assigned to same HydroRiver_ID  add True else False
all_pairs_dup['same_river_id'] = np.where(all_pairs_dup['x_NEAR_FID']==all_pairs_dup['y_NEAR_FID'],True, False)
print(all_pairs_dup[all_pairs_dup['same_river_id']==False])
diff_river_id  =all_pairs_dup[all_pairs_dup['same_river_id']==False]

# save file containing list of pot_duplicated stations origin from different countries
diff_river_id.to_csv(f'../../output_data/merge_0km_dist_stations/diff_river_id_{thrs}_km.csv')

                               x                          y distance_km  \
103           ('GRQA', '100168')  ('GRQA', 'USGS-01334500')      0.1097
107           ('GRQA', '100173')  ('GRQA', 'USGS-01342800')      0.2409
224           ('GRQA', '100364')  ('GRQA', 'USGS-01470640')      0.2317
246           ('GRQA', '100413')  ('GRQA', 'USGS-01485000')      0.1543
270           ('GRQA', '100446')      ('USGS', 'paWQN0229')      0.2445
...                          ...                        ...         ...
14960  ('germany', 'ST_2110050')  ('germany', 'ST_2110060')       0.152
14966  ('germany', 'ST_2110906')  ('germany', 'ST_2110907')      0.1949
14991   ('germany', 'ST_310030')   ('germany', 'ST_310610')      0.2313
15017   ('germany', 'ST_410171')   ('germany', 'ST_410175')      0.2194
15035   ('germany', 'ST_413820')   ('germany', 'ST_413829')      0.2447

                    x_station_id x_data_sourc x_country        x_area  \
103           ('GRQA', '100168')      GLORICH       USA  1.339140e+09
107           ('GRQA', '100173')      GLORICH       USA  5.044945e+08
224           ('GRQA', '100364')      GLORICH       USA  7.341308e+07
246           ('GRQA', '100413')      GLORICH       USA  1.819102e+08
270           ('GRQA', '100446')      GLORICH       USA  8.244913e+08
...                          ...          ...       ...           ...
14960  ('germany', 'ST_2110050')         GDS1   Germany -9.999000e+03
14966  ('germany', 'ST_2110906')         GDS1   Germany -9.999000e+03
14991   ('germany', 'ST_310030')         GDS1   Germany  1.201040e+04
15017   ('germany', 'ST_410171')         GDS1   Germany -9.999000e+03
15035   ('germany', 'ST_413820')         GDS1   Germany -9.999000e+03

           x_lat      x_lon  x_NEAR_FID  ...               y_station_id  \
103    42.939592 -73.377085     7519292  ...  ('GRQA', 'USGS-01334500')
107    43.393590 -74.860695     7507290  ...  ('GRQA', 'USGS-01342800')
224    40.656713 -75.844066     7581932  ...  ('GRQA', 'USGS-01470640')
246    38.389591 -75.322918     7639789  ...  ('GRQA', 'USGS-01485000')
270    40.869065 -77.047361     7576574  ...      ('USGS', 'paWQN0229')
...          ...        ...         ...  ...                        ...
14960  51.858416  12.057272     1855243  ...  ('germany', 'ST_2110060')
14966  51.858133  12.646506     1854017  ...  ('germany', 'ST_2110907')
14991  51.289382  12.061858     1869721  ...   ('germany', 'ST_310610')
15017  51.930331  11.515818     1852049  ...   ('germany', 'ST_410175')
15035  52.293970  11.694920     1842228  ...   ('germany', 'ST_413829')

      y_data_sourc y_country    y_area      y_lat      y_lon  y_NEAR_FID  \
103            WQP       USA   510.000  42.938611 -73.376944     7519541
107            WQP       USA   193.000  43.395556 -74.859444     7506717
224            WQP       USA    26.800  40.654815 -75.845198     7582486
246            WQP       USA    60.500  38.388889 -75.324444     7639891
270         PA DEP       USA   792.072  40.867200 -77.048900     7576573
...            ...       ...       ...        ...        ...         ...
14960         GDS1   Germany -9999.000  51.859764  12.056911     1853899
14966         GDS1   Germany -9999.000  51.856381  12.646481     1854016
14991         GDS1   Germany -9999.000  51.289650  12.065155     1869134
15017         GDS1   Germany -9999.000  51.930344  11.519016     1852278
15035         GDS1   Germany -9999.000  52.295764  11.697004     1842229

       y_NEAR_DIST  same_country  same_river_id
103      73.096471          True          False
107      54.542011          True          False
224     122.461108          True          False
246      57.204041          True          False
270      82.898764          True          False
...            ...           ...            ...
14960    72.650897          True          False
14966    14.541462          True          False
14991     7.413837          True          False
15017   268.275399          True          False
15035   654.959496          True          False

[561 rows x 21 columns]

## 7. save lists of potential duplicated stations:

In [22]:
# save files to csv:
all_pairs_dup.to_csv(f'../../output_data/merge_0km_dist_stations/all_pairs_pot_dup{thrs}km_with_infos.csv')